name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Format
      run: cargo fmt -- --check
    - name: Install SQLX
      run: cargo install sqlx-cli
    - name: Run POSTGRESS
      run:  ./scripts/init_db.sh
    - name: Check  Offline SQL
      run: cargo sqlx prepare --check -- --bin zero2prod
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
